apiVersion: apps/v1 # k apply -f query-depl.yaml
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query # find all the pods with the label of app posts
  template:
    metadata:
      labels:
        app: query # we want the pod to have label of posts
    spec:
      containers: # array of images
        - name:  query
          image: btabe0914/query # use latest tag
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: ClusterIP # expose pods to outside worlds
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
